server:
  port: 80
  error:
    include-message: always
    include-stacktrace: on_param
spring:
  datasource:
    url: jdbc:h2:./db/genealogy;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: sa
    password: sa
  jpa:
    show-sql: true
security:
  secret: kdskliojfsdl32r3hhkjdfdf
  token:
    exp: 10 #days
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    com.koldyr.genealogy.utils.GenealogyLogger: DEBUG

#    schema: classpath:sql/schema.sql
#    initialization-mode: always

---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8081
  address: 10.92.92.22
