server:
  port: 80
  error:
    include-message: always
    include-stacktrace: on_param
spring:
  datasource:
    url: jdbc:h2:./db/genealogy;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: sa
    password: sa
  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 10
          order_inserts: true
          order_updates: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
security:
  secret: kdskliojfsdl32r3hhkjdfdf
  token:
    exp: 10 #days

#    schema: classpath:sql/schema.sql
#    initialization-mode: always

---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8081
  address: 10.92.92.22

---
spring:
  config:
    activate:
      on-profile: int-test
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  jpa:
    show-sql: true
    generate-ddl: true
