server:
  port: 80
  error:
    include-message: always
    include-stacktrace: on_param
spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/genealogy
    username: xxx
    password: xxx
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 10
          order_inserts: true
          order_updates: true
  liquibase:
    enabled: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    default-property-inclusion: non_null
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: HS256
          jwk-set-uri: http://localhost/.well-known/jwk.json
    secret: f4adc177-5aa5-4011-8c23-d6601bbbc94e
    token:
      exp: 10 #minutes

#    schema: classpath:sql/schema.sql
#    initialization-mode: always

---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: int-test
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: xxx
    password: xxx
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    generate-ddl: true
  test:
    username: xxx
    password: xxx
