### Login
POST http://{{server}}/api/user/login
Content-Type: application/json
Accept: */*

{
  "username": "me@koldyr.com",
  "password": {{testUserPwd}}
}

### Get Families
GET http://{{server}}/api/lineage/1/families
Authorization: Bearer {{authToken}}
Accept: application/json

### Get Family
GET http://{{server}}/api/lineage/1/families/1
Authorization: Bearer {{authToken}}
Accept: application/json

### Create Family
POST http://{{server}}/api/lineage/1/families
Authorization: Bearer {{authToken}}
Content-Type: application/json
Accept: application/json

{
  "husband": 1,
  "wife": 2
}

### Update Family
POST http://{{server}}/api/lineage/1/families/1
Authorization: Bearer {{authToken}}
Content-Type: application/json
Accept: application/json

{
  "husband": 1,
  "wife": 2
}

### Delete Family
DELETE http://{{server}}/api/lineage/1/families/2
Authorization: Bearer {{authToken}}

### Create Child in Family
POST http://{{server}}/api/lineage/1/families/1/children
Authorization: Bearer {{authToken}}
Content-Type: application/json
Accept: application/json

{
  "name": {
    "first": "p5_name",
    "middle": "p5_middle",
    "last": "p5_last"
  },
  "gender": "FEMALE",
  "place": "p5_place",
  "occupation": "p5_occup",
  "note": "p5_note"
}

### Add Child to Family
PATCH http://{{server}}/api/lineage/1/families/1/children/5
Authorization: Bearer {{authToken}}
Accept: application/json

### Delete Child from Family
DELETE http://{{server}}/api/lineage/1/families/1/children/5
Authorization: Bearer {{authToken}}
Accept: application/json

###
GET http://{{server}}/api/lineage/1/families/1/children
Authorization: Bearer {{authToken}}
Accept: application/json

### Create Family Event
POST http://{{server}}/api/lineage/1/families/1/events
Authorization: Bearer {{authToken}}
Content-Type: application/json
Accept: application/json

{
  "type": "ENGA",
  "date": "2000-08-22",
  "place": "Minsk, Belarus",
  "note": "f1 Engagement event"
}

### Get Family Events
GET http://{{server}}/api/lineage/1/families/1/events
Authorization: Bearer {{authToken}}
Accept: application/json

### Delete Family Event
DELETE http://{{server}}/api/lineage/1/families/1/events/6
Authorization: Bearer {{authToken}}
Accept: application/json

