GET http://localhost:8080/api/genealogy/person/

###
GET http://localhost:8080/api/genealogy/person/6
Accept: application/json

### Create Person
POST http://localhost:8080/api/genealogy/person/
Content-Type: application/json

{
  "name": {
    "first": "p4_name",
    "middle": "p4_middle",
    "last": "p4_last"
  },
  "gender": "MALE",
  "place": "p4_place",
  "occupation": "p4_occup",
  "note": "p4_note"
}

###
PUT http://localhost:8080/api/genealogy/person/4
Content-Type: application/json

{
  "name": {
    "first": "p4_name",
    "middle": "p4_middle",
    "last": "p4_last"
  },
  "gender": "FEMALE",
  "place": "p4_place",
  "occupation": "p4_occup",
  "note": "p4_note"
}

###
DELETE http://localhost:8080/api/genealogy/person/1

###
POST http://localhost:8080/api/genealogy/person/2/event
Content-Type: application/json

{
  "type": "OCCU",
  "date": "2021-09-22",
  "place": "Minsk, Belarus",
  "note": "Test event2"
}

###
GET http://localhost:8080/api/genealogy/person/1/event
Accept: application/json

###
GET http://localhost:8080/api/genealogy/family/
Accept: application/json

###
POST http://localhost:8080/api/genealogy/family/
Content-Type: application/json

{
  "husband": 2,
  "wife": 1
}

###
POST http://localhost:8080/api/genealogy/family/1/children
Content-Type: application/json

{
  "husband": 2,
  "wife": 1
}

###
GET http://localhost:8080/api/genealogy/family/1/children
Accept: application/json


