### User login
POST http://{{server}}/api/v1/user/login
Content-Type: application/json

{
  "username": "me@koldyr.com",
  "password": "{{testUserPwd}}"
}

### Import Lineage
POST http://{{server}}/api/v1/lineage/import
Authorization: Bearer {{authToken}}
Content-Type: text/ged
Lineage-Name: Test Lineage GED

< ../test-lineage.ged

### Get all Lineages
GET http://{{server}}/api/v1/lineage
Authorization: Bearer {{authToken}}
Accept: application/json

### Get Lineage
GET http://{{server}}/api/v1/lineage/2
Authorization: Bearer {{authToken}}
Accept: application/json

### Create new Lineage
POST http://{{server}}/api/v1/lineage
Authorization: Bearer {{authToken}}
Content-Type: application/json
Accept: application/json

{
  "name": "Test 3",
  "note": "Test 3"
}

### Delete Lineage
DELETE http://{{server}}/api/v1/lineage/4
Authorization: Bearer {{authToken}}

### Update Lineage
PUT http://{{server}}/api/v1/lineage/import
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "",
  "note": ""
}

### Export Lineage
GET http://{{server}}/api/v1/lineage/2/export
Authorization: Bearer {{authToken}}
Accept: text/ged
