### Login
POST http://localhost/api/user/login
Content-Type: application/json

{
  "username": "me@koldyr.com",
  "password": "koldyr"
}

### Registration
POST http://localhost/api/user/registration
Content-Type: application/json

{
  "email": "me@koldyr.com",
  "password": "koldyr",
  "name": "me",
  "surName": "koldyr"
}

### Get All Persons
GET http://localhost/api/genealogy/persons
Authorization: Bearer {{authToken}}

### Get Person By ID
GET http://localhost/api/genealogy/persons/1
Authorization: Bearer {{authToken}}
Accept: application/json

### Create Person
POST http://localhost/api/genealogy/persons
Authorization: Bearer {{authToken}}
Content-Type: application/json
Accept: application/json

{
  "name": {
    "first": "p5_name",
    "middle": "p5_middle",
    "last": "p5_last"
  },
  "gender": "MALE",
  "place": "p5_place",
  "occupation": "p5_occup",
  "note": "p5_note"
}

### Update Person
PUT http://localhost/api/genealogy/persons/33
Authorization: Bearer {{authToken}}
Content-Type: application/json
Accept: application/json

{
  "name": {
    "first": "p33_name",
    "middle": "p33_middle",
    "last": "p33_last"
  },
  "gender": "FEMALE",
  "place": "p33_place",
  "occupation": "p33_occup",
  "note": "p33_note"
}

### Delete Person
DELETE http://localhost/api/genealogy/persons/33

### Create Person Event
POST http://localhost/api/genealogy/persons/1/events
Authorization: Bearer {{authToken}}
Content-Type: application/json
Accept: application/json

{
  "type": "EDUC",
  "date": "1982-09-22",
  "place": "Baranovichi, Belarus",
  "note": "p1 EDUC"
}

### Get Person Events
GET http://localhost/api/genealogy/persons/1/events
Authorization: Bearer {{authToken}}
Accept: application/json

### Delete Person Event
DELETE http://localhost/api/genealogy/persons/1/events/10
Authorization: Bearer {{authToken}}
Accept: application/json
