### User registration
POST http://{{server}}/api/v1/user/registration
Content-Type: application/json

{
  "name": "me",
  "surName": "koldyr",
  "email": "me@koldyr.com",
  "password": "{{testUserPwd}}"
}

### User login
POST http://{{server}}/api/v1/user/login
Content-Type: application/json

{
  "username": "me@koldyr.com",
  "password": "{{testUserPwd}}"
}

### Get All Persons
GET http://{{server}}/api/v1/lineage/1/persons
Authorization: Bearer {{authToken}}

### Get Person By ID
GET http://{{server}}/api/v1/lineage/1/persons/11
Authorization: Bearer {{authToken}}
Accept: application/json

### Create Person
POST http://{{server}}/api/v1/lineage/1/persons
Authorization: Bearer {{authToken}}
Content-Type: application/json
Accept: application/json

{
  "name": {
    "first": "p5_name",
    "middle": "p5_middle",
    "last": "p5_last"
  },
  "gender": "MALE",
  "place": "p5_place",
  "occupation": "p5_occup",
  "note": "p5_note"
}

### Update Person
PUT http://{{server}}/api/v1/lineage/1/persons/1
Authorization: Bearer {{authToken}}
Content-Type: application/json
Accept: application/json

{
  "name": {
    "first": "p33_name",
    "middle": "p33_middle",
    "last": "p33_last"
  },
  "gender": "FEMALE",
  "place": "p33_place",
  "occupation": "p33_occup",
  "note": "p33_note"
}

### Delete Person
DELETE http://{{server}}/api/v1/lineage/1/persons/11

### Create Person Event
POST http://{{server}}/api/v1/lineage/1/persons/1/events
Authorization: Bearer {{authToken}}
Content-Type: application/json
Accept: application/json

{
  "type": "EDUC",
  "date": "1982-09-22",
  "place": "Baranovichi, Belarus",
  "note": "p1 EDUC"
}

### Get Person Events
GET http://{{server}}/api/v1/lineage/1/persons/1/events
Authorization: Bearer {{authToken}}
Accept: application/json

### Delete Person Event
DELETE http://{{server}}/api/v1/lineage/1/persons/1/events/1
Authorization: Bearer {{authToken}}
Accept: application/json

### Create Person Photo
POST http://{{server}}/api/v1/lineage/1/persons/1/photo
Authorization: Bearer {{authToken}}
Content-Type: image/jpeg

< C:\Dist\avatar0.jpg

### Get Person Photo
GET http://{{server}}/api/v1/lineage/1/persons/1/photo
Authorization: Bearer {{authToken}}

### Person Search
POST http://{{server}}/api/v1/lineage/1/persons/search
Authorization: Bearer {{authToken}}
Content-Type: application/json
Accept: application/json

{
  "name": "p3"
}
