alter table T_PERSON drop constraint FK_PERSON_FAMILY;
alter table T_PERSON drop constraint FK_PERSON_PARENT_FAMILY;

alter table T_FAMILY drop constraint FK_FAMILY_FATHER;
alter table T_FAMILY drop constraint FK_FAMILY_MOTHER;

DROP TABLE T_FAMILY_EVENT;
DROP TABLE T_PERSON_EVENT;
DROP TABLE T_CHILDREN;
DROP TABLE T_LIFE_EVENT;
DROP TABLE T_PERSON;
DROP TABLE T_FAMILY;

DROP SEQUENCE SEQ_PERSON;
DROP SEQUENCE SEQ_FAMILY;
DROP SEQUENCE SEQ_EVENT;
