CREATE USER trx_user password 'xxx';

GRANT SELECT, INSERT, UPDATE, DELETE ON T_LINEAGE TO trx_user;
GRANT SELECT, UPDATE ON SEQ_LINEAGE TO trx_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON T_PERSON TO trx_user;
GRANT SELECT, UPDATE ON SEQ_PERSON TO trx_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON T_FAMILY TO trx_user;
GRANT SELECT, UPDATE ON SEQ_FAMILY TO trx_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON T_CHILDREN TO trx_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_PERSON_EVENT TO trx_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_FAMILY_EVENT TO trx_user;
GRANT SELECT, UPDATE ON SEQ_EVENT TO trx_user;

GRANT SELECT, INSERT, UPDATE ON T_USER TO trx_user;
GRANT SELECT, UPDATE ON SEQ_USER TO trx_user;

GRANT SELECT ON T_ROLE TO trx_user;
