CREATE TABLE IF NOT EXISTS T_PERSON
(
    PERSON_ID        INTEGER PRIMARY KEY,
    PLACE            VARCHAR(256),
    OCCUPATION       VARCHAR(256),
    NOTE             VARCHAR(256),
    GENDER           CHAR(1),
    NAME             VARCHAR(256),
    MIDDLE           VARCHAR(256),
    LAST             VARCHAR(256),
    MAIDEN           VARCHAR(256),
    PARENT_FAMILY_ID INTEGER,
    FAMILY_ID        INTEGER
);

CREATE TABLE IF NOT EXISTS T_FAMILY
(
    FAMILY_ID INTEGER PRIMARY KEY,
    MOTHER_ID INTEGER,
    FATHER_ID INTEGER
);

CREATE TABLE IF NOT EXISTS T_CHILDREN
(
    FAMILY_ID INTEGER,
    CHILD_ID  INTEGER
);

CREATE TABLE IF NOT EXISTS T_LIFE_EVENT
(
    EVENT_ID INTEGER PRIMARY KEY,
    TYPE     VARCHAR(256),
    PREFIX   VARCHAR(256),
    PLACE    VARCHAR(256),
    NOTE     VARCHAR(256),
    DATE     TIMESTAMP
);

CREATE TABLE IF NOT EXISTS T_PERSON_EVENT
(
    PERSON_ID INTEGER,
    EVENT_ID  INTEGER
);

CREATE TABLE IF NOT EXISTS T_FAMILY_EVENT
(
    FAMILY_ID INTEGER,
    EVENT_ID  INTEGER
);

alter table T_PERSON
    add FOREIGN KEY (PARENT_FAMILY_ID) REFERENCES T_FAMILY (FAMILY_ID);
alter table T_PERSON
    add FOREIGN KEY (FAMILY_ID) REFERENCES T_FAMILY (FAMILY_ID);

alter table T_FAMILY
    add FOREIGN KEY (MOTHER_ID) REFERENCES T_PERSON (PERSON_ID);
alter table T_FAMILY
    add FOREIGN KEY (FATHER_ID) REFERENCES T_PERSON (PERSON_ID);

alter table T_CHILDREN
    add FOREIGN KEY (FAMILY_ID) REFERENCES T_FAMILY (FAMILY_ID);
alter table T_CHILDREN
    add FOREIGN KEY (CHILD_ID) REFERENCES T_PERSON (PERSON_ID);

alter table T_PERSON_EVENT
    add FOREIGN KEY (PERSON_ID) REFERENCES T_PERSON (PERSON_ID);
alter table T_PERSON_EVENT
    add FOREIGN KEY (EVENT_ID) REFERENCES T_LIFE_EVENT (EVENT_ID);

alter table T_FAMILY_EVENT
    add FOREIGN KEY (FAMILY_ID) REFERENCES T_FAMILY (FAMILY_ID);
alter table T_FAMILY_EVENT
    add FOREIGN KEY (EVENT_ID) REFERENCES T_LIFE_EVENT (EVENT_ID);
